bot:
  token: $BOT_TOKEN
  username: $BOT_USERNAME
  groupId: ${GROUP_ID}
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:folks.sqlite:folks?cache=shared
    username: sa
    password: sa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


