bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  groupId: ${GROUP_ID}
  group-users:
    - @vasyl_bhd
    - @candy_rain


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/folks
    username: admin
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


